- name: Install PHP Remi Repository
  yum: name=https://rpms.remirepo.net/enterprise/remi-release-8.rpm update_cache=yes state=latest disable_gpg_check=True
 
- name: Enable PHP Remi Repository
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y
 
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"